name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NAME=LUKAS NAHUEL
    - CLI_SURNAME=DE ANGELIS RIVA
    - CLI_DOCUMENT=42340222
    - CLI_BIRTHDATE=2000-01-06
    - CLI_NUMBER=91218
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NAME=KEVIN
    - CLI_SURNAME=DE ANGELIS RIVA
    - CLI_DOCUMENT=44340223
    - CLI_BIRTHDATE=2002-10-15
    - CLI_NUMBER=1234
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NAME=KIARA LAURA
    - CLI_SURNAME=DE ANGELIS RIVA
    - CLI_DOCUMENT=45131002
    - CLI_BIRTHDATE=2004-04-15
    - CLI_NUMBER=9941
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client4:
    container_name: client4
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=4
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NAME=DIEGO
    - CLI_SURNAME=DE ANGELIS
    - CLI_DOCUMENT=22000112
    - CLI_BIRTHDATE=1971-06-20
    - CLI_NUMBER=8188
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client5:
    container_name: client5
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=5
    - CLI_LOG_LEVEL=DEBUG
    - CLI_NAME=VIRGINIA LAURA
    - CLI_SURNAME=RIVA
    - CLI_DOCUMENT=23123456
    - CLI_BIRTHDATE=1972-12-12
    - CLI_NUMBER=1212
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
version: '3.9'
