name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - CLI_BETS_FILE=agency-1.csv
    - CLI_BETS_BATCH_SIZE=50
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/agency-1.csv:/agency-1.csv
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - CLI_LOG_LEVEL=DEBUG
    - CLI_BETS_FILE=agency-2.csv
    - CLI_BETS_BATCH_SIZE=100
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/agency-2.csv:/agency-2.csv
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - CLI_LOG_LEVEL=DEBUG
    - CLI_BETS_FILE=agency-3.csv
    - CLI_BETS_BATCH_SIZE=150
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/agency-3.csv:/agency-3.csv
  client4:
    container_name: client4
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=4
    - CLI_LOG_LEVEL=DEBUG
    - CLI_BETS_FILE=agency-4.csv
    - CLI_BETS_BATCH_SIZE=200
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/agency-4.csv:/agency-4.csv
  client5:
    container_name: client5
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=5
    - CLI_LOG_LEVEL=DEBUG
    - CLI_BETS_FILE=agency-5.csv
    - CLI_BETS_BATCH_SIZE=250
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/agency-5.csv:/agency-5.csv
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
version: '3.9'
